Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,8 +11,8 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Simulate failure
-        run: echo "BUILDING..." 
-        #run: exit 1  # This will fail the job
+        #run: echo "BUILDING..." 
+        run: exit 1  # This will fail the job
 
       - name: Notify Slack on success
         if: success()
